spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://root:password@mongodb:27017/majestic_db?authSource=admin
  docker:
    compose:
      enabled: true
      file: compose.yaml
  security:
    user:
      name: user
      password: user


logging:
  level:
    org:
      springframework:
        security: TRACE
    ma:
      youcode:
        majesticcup:
          filters:
            JwtAuthFilter: DEBUG